//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTestToXunitConverter.xUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsTestToXunitConverter.xUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///
        ///namespace MsTestToXunitConverter.xUnit.Resources
        ///{
        ///    class TestInitializeA
        ///    {
        ///        [TestInitialize]
        ///        public void TestInitialize()
        ///        {
        ///
        ///        }
        ///    }
        ///
        ///    class TestInitializeB
        ///    {
        ///        TestInitializeB()
        ///        {
        ///            var x = 1 + 2;
        ///        }
        ///
        ///        [TestInitialize]
        ///        publi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestClasses {
            get {
                return ResourceManager.GetString("TestClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Xunit;
        ///
        ///namespace MsTestToXunitConverter.xUnit.Resources
        ///{
        ///    class TestInitializeA
        ///    {
        ///        public void TestInitialize()
        ///        {
        ///        }
        ///
        ///        TestInitializeA()
        ///        {
        ///            TestInitialize();
        ///        }
        ///    }
        ///
        ///    class TestInitializeB
        ///    {
        ///        TestInitializeB()
        ///        {
        ///            var x = 1 + 2;
        ///            TestInitialize();
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestClasses_out {
            get {
                return ResourceManager.GetString("TestClasses_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using System.Linq;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///
        ///namespace MsTestToXunitConverter.xUnit.Resources
        ///{
        ///    class TestInvocations
        ///    {
        ///        public void TestAreEqual()
        ///        {
        ///            Assert.AreEqual(1, 1);
        ///        }
        ///
        ///        public void TestAreNotEqual()
        ///        {
        ///            Assert.AreNotEqual(1, 2);
        ///        }
        ///
        ///        public void TestAreSame()
        ///        {
        ///            var o = &quot;something&quot;;
        ///            Assert.AreSame(o, o);
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestInvocations {
            get {
                return ResourceManager.GetString("TestInvocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using System.Linq;
        ///using Xunit;
        ///
        ///namespace MsTestToXunitConverter.xUnit.Resources
        ///{
        ///    class TestInvocations
        ///    {
        ///        public void TestAreEqual()
        ///        {
        ///            Assert.Equal(1, 1);
        ///        }
        ///
        ///        public void TestAreNotEqual()
        ///        {
        ///            Assert.NotEqual(1, 2);
        ///        }
        ///
        ///        public void TestAreSame()
        ///        {
        ///            var o = &quot;something&quot;;
        ///            Assert.Same(o, o);
        ///        }
        ///
        ///        public void TestContains()
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestInvocations_out {
            get {
                return ResourceManager.GetString("TestInvocations_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///
        ///namespace MsTestToXunitConverter.xUnit.Resources
        ///{
        ///    public class FactTest
        ///    {
        ///        [TestMethod]
        ///        public void TestMethodA()
        ///        {
        ///
        ///        }
        ///
        ///		[Description(&quot;Description&quot;)]
        ///		public void DescriptionA()
        ///        {
        ///
        ///        }
        ///
        ///		[TestMethod][Description(&quot;Description&quot;)]
        ///		public void DescriptionB()
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestMethods {
            get {
                return ResourceManager.GetString("TestMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Xunit;
        ///
        ///namespace MsTestToXunitConverter.xUnit.Resources
        ///{
        ///    public class FactTest
        ///    {
        ///        [Fact]
        ///        public void TestMethodA()
        ///        {
        ///
        ///        }
        ///
        ///        [Fact(DisplayName = &quot;Description&quot;)]
        ///        public void DescriptionA()
        ///        {
        ///
        ///        }
        ///
        ///        [Fact(DisplayName = &quot;Description&quot;)]
        ///        public void DescriptionB()
        ///        {
        ///
        ///        }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestMethods_out {
            get {
                return ResourceManager.GetString("TestMethods_out", resourceCulture);
            }
        }
    }
}
